# Hypertools Analyze

The hypertools analyze feature allows you to pass simple arguments to normalize, align, and reduce datasets with only one line of code! 

Data is returned as a list of numpy arrays.

## Import the package

In [1]:
import hypertools as hyp

## Load your data

In this case, we have used one of the sample datasets built into the package

In [4]:
weights = hyp.load('weights_avg')

We can take a cursory look at the data structure (namely, the type and size of 'weights' and its components)

In [6]:
print("Length: " + str(len(weights))); print("Type: " + str(type(weights))); print(); print('Each element contains a '+ str(type(weights[0][0]))+' consisting of '+ str(type(weights[0][0][0]))+'s')

Length: 2
Type: <class 'list'>

Each element contains a <class 'numpy.ndarray'> consisting of <class 'numpy.float32'>s


## Normalization

Normalize accepts the following arguments, as strings:
+ ‘across’ - z-scores data with repect to column n across all arrays passed in the list (default)

+ ‘within’ - z-scores columns within each list that is passed 

+ ‘row’ - z-scores each row of data

Here is an example where we z-score the columns within each list:

In [23]:
hyp.analyze(weights, normalize='within')

[array([[ 6.46877527,  0.04415582,  2.46139169, ...,  3.1587286 ,
          5.03870821,  1.15433145],
        [ 3.298666  ,  0.34712252,  0.55772746, ..., -0.90643823,
          2.45424342, -0.6624018 ],
        [-0.08597342,  0.33172083,  0.33688417, ..., -0.91683173,
          1.40573359, -0.43677449],
        ..., 
        [-1.86581433, -0.04198547,  3.06311655, ...,  2.97605228,
         -0.01176681,  4.2177    ],
        [-1.09020317, -1.03223801,  3.21619081, ...,  1.80767441,
         -0.47513825,  5.51226616],
        [-1.37564707, -0.3927514 ,  2.98111844, ...,  0.25864044,
         -0.99671048,  5.56884575]], dtype=float32),
 array([[ 4.59447861, -0.34858733,  1.80348003, ...,  0.38786319,
          4.09196997,  1.77377677],
        [ 2.43848038,  0.37334016,  0.08044791, ...,  0.03241993,
          1.83599603, -0.36308572],
        [ 1.24563742,  1.65509987,  0.08995987, ..., -1.67206371,
          1.21683633, -0.65195262],
        ..., 
        [-0.8509773 , -0.52303195,  2

## Normalize and reduce

To easily normalize and reduce data, pass the normalize, reduce, and ndims arguments to hyp.analyze!

The normalize argument, outlined above, specifies how the data should be normalized. reduce, which can accept a string, takes the desired method of reduction. ndims, which takes an int, specifies the numebr of dimensions to reduce to.

Supported models: PCA, IncrementalPCA, SparsePCA, MiniBatchSparsePCA, KernelPCA, FastICA, FactorAnalysis, TruncatedSVD, DictionaryLearning, MiniBatchDictionaryLearning, TSNE, Isomap, SpectralEmbedding, LocallyLinearEmbedding, and MDS. 

In [32]:
hyp.analyze(weights, normalize='within', reduce='PCA', ndims=3)

[array([[  2.74743729e+01,  -3.92151666e+00,  -2.26234436e+00],
        [  1.10754519e+01,  -5.77201366e-01,   2.10350657e+00],
        [  4.60648775e+00,   4.30045652e+00,   3.88469243e+00],
        [  2.78833723e+00,   3.83656359e+00,   3.55523157e+00],
        [  1.97615814e+00,   1.93675709e+00,   3.45056438e+00],
        [  1.64023483e+00,   2.28412151e+00,   2.26816344e+00],
        [  5.97433209e-01,   2.16145134e+00,   2.60946655e+00],
        [  7.44886175e-02,   2.47124290e+00,   3.33965850e+00],
        [ -1.26508772e+00,   2.63727117e+00,   3.22769260e+00],
        [ -7.87248492e-01,   2.36424565e+00,   4.01809168e+00],
        [  7.29112387e-01,   3.66632295e+00,   3.23376083e+00],
        [  2.14658713e+00,   2.77926397e+00,   2.52658081e+00],
        [  2.12321472e+00,   2.63510466e+00,   1.77159595e+00],
        [  1.00192979e-01,   2.22475243e+00,   9.41944957e-01],
        [ -4.02779484e+00,   2.37618208e+00,   1.48858285e+00],
        [ -2.84852147e+00,   1.17393899e

### Parameter specifications

For finer control of the model parameters, you may prefer to pass reduce a dictionary. See scikit-learn specific model docs for details on parameters supported for each model.

In [37]:
# dictionary of parameters
reduce={'model' : 'PCA', 'params' : {'whiten' : True}}

hyp.analyze(weights, normalize='within', reduce=reduce, ndims=3)

[array([[ 5.8384223 , -1.13047218, -0.82379657, ..., -0.63713217,
         -0.82165867, -1.11516368],
        [ 2.35358191, -0.16639392,  0.76596439, ..., -0.2222349 ,
          1.01458609,  2.20212412],
        [ 0.97889817,  1.23971081,  1.41455555, ..., -0.91401982,
          0.54540199,  2.58263707],
        ..., 
        [ 3.52915692,  2.97692466,  1.17344344, ...,  0.55327153,
          0.98111576, -0.82304412],
        [ 3.21214128,  2.71781754,  1.62019217, ...,  0.06156633,
         -1.45747936,  0.73908371],
        [ 2.40363932,  2.71607685,  2.16388583, ...,  0.63522768,
         -1.16778553, -1.31602693]], dtype=float32),
 array([[ 4.22466707,  0.41409388, -0.83021832, ...,  0.63574553,
          0.99074155, -0.80069089],
        [ 1.65258086,  0.456433  ,  0.11900186, ...,  0.05798182,
          0.73506439, -1.05233908],
        [ 1.46180117,  0.72621256,  0.0373362 , ...,  0.3000766 ,
         -0.96149111, -0.31388852],
        ..., 
        [ 3.693784  ,  2.90511012,  1

## Normalize, reduce, and align

You may wish to align normalized and reduced data.
(We like this feature because it facilitates plotting multiple high-dimensional datasets in a common, low-dimensional space.)

The align argument can accept the following strings:
+ 'hyper' - implements hyperalignment algorithm
+ 'SRM' - implements shared response mode


In [38]:
hyp.analyze(weights, normalize='within', reduce='PCA', ndims=3, align='SRM')

[array([[ -1.90348591e+01,   1.92159936e+01,  -6.61493688e+00],
        [ -8.63230735e+00,   7.26643568e+00,   3.25141878e-01],
        [ -6.68359299e+00,  -2.77682550e-01,   3.17127233e+00],
        [ -4.93115648e+00,  -1.02353691e+00,   3.12566540e+00],
        [ -3.13163412e+00,  -2.96410023e-03,   3.12337679e+00],
        [ -2.93791208e+00,  -6.05060908e-01,   2.01363371e+00],
        [ -2.08146139e+00,  -1.09085776e+00,   2.51309806e+00],
        [ -1.94157054e+00,  -1.57111225e+00,   3.32081603e+00],
        [ -9.72254269e-01,  -2.51156235e+00,   3.42351017e+00],
        [ -1.27685621e+00,  -1.92599028e+00,   4.12488522e+00],
        [ -3.16679329e+00,  -2.14591634e+00,   3.13004813e+00],
        [ -3.66637646e+00,  -6.71362862e-01,   2.19606710e+00],
        [ -3.47250425e+00,  -6.50492437e-01,   1.45222014e+00],
        [ -1.53223821e+00,  -1.61390071e+00,   9.45723461e-01],
        [  1.56776115e+00,  -4.13016141e+00,   2.13755541e+00],
        [  1.38419776e+00,  -2.48966435e

### Parameter specifications

You can also pass a dictionary for finer control, where the ‘model’ key is a string that specifies the model and the params key is a dictionary of parameter values (default : ‘hyper’).

In [8]:
# dictionary of parameters
reduce={'model' : 'PCA', 'params' : {'whiten' : True}}

hyp.analyze(weights, normalize='within', reduce=reduce, ndims=3, align='SRM')

[array([[-3.48066558, -1.29626739, -0.93544699, ...,  0.19677619,
          2.1331637 , -1.38228965],
        [-1.4971815 , -0.21635239,  1.08006662, ..., -0.02345183,
         -1.57698471, -0.50602953],
        [ 0.57623712, -0.82443388, -0.91056472, ..., -1.20161248,
         -1.28732839,  0.98984724],
        ..., 
        [-0.76034672,  1.72198298,  0.11710264, ...,  0.0735719 ,
         -0.33986306, -0.82348325],
        [-2.11684782,  1.15797435, -0.67519646, ..., -0.38156124,
         -0.13261874,  0.31055954],
        [-1.16829724, -1.03453552,  0.27661793, ...,  0.49027704,
         -1.80316953, -0.45703233]]),
 array([[-3.08528338, -0.60776885, -0.21407866, ..., -0.5404774 ,
          2.17432262, -0.89459908],
        [-1.23179388, -0.13663236,  0.36849339, ...,  0.23493341,
         -0.62566314, -0.8658519 ],
        [ 0.85926003, -0.54749495, -1.17357368, ..., -0.35597533,
         -2.15213509,  0.86965651],
        ..., 
        [-0.4476563 ,  0.1991326 ,  0.04259137, ...,